channels:
  - bioconda
dependencies:
  - bowtie2
  - fastqc
  - trim-galore
  - multiqc
  - samtools
  - bamtools
  - bismark
  - python > 3
  - pandas
  - cutadapt
  - ucsc-bedgraphtobigwig
  - deeptools>=3
  - biopython=1.78
